### ISSUE TITLE
Error for salesforce metadata retrieve

### ISSUE THREAD

**Issue by chashmeetsingh** [jsforce/jsforce#1141]
```buffer.js:333
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at Function.from (buffer.js:333:9)
    at /home/runner/work/sf-core/sf-core/backup-scripts/node_modules/jsforce/lib/api/metadata.js:774:34
    at /home/runner/work/sf-core/sf-core/backup-scripts/node_modules/jsforce/lib/promise.js:72:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_INVALID_ARG_TYPE'```

**Comment by chashmeetsingh** [comment]
```const stream = status.sfConnection.metadata.retrieve({ 
                                        apiVersion: '51.0',
                                        singlePackage: true,
                                        unpackaged: {
                                            types: _types
                                        }
                                    }).stream().pipe(fs.createWriteStream(status.tempPath+status.zipPath+status.zipFile));```

**Comment by cristiand391** [comment]
triaging old issues...

closing as it's very likely a dup of https://github.com/jsforce/jsforce/issues/1302
