### ISSUE TITLE
Error: Cannot create a string longer than 0xffffff0 characters

### ISSUE THREAD

**Issue by vpetrovych** [jsforce/jsforce#1143]
I'm trying to backup Accounts by using jsforce Bulk API and querying for all records.
There are 2,660,000 records.
I'm using jsforce 1.10.1

When I try to run the bulk api and use stream it throws the error:
```
Error: Cannot create a string longer than 0xffffff0 characters
    at Buffer.toString (buffer.js:799:17)
    at Request.<anonymous> (C:\Users\w102057\Developer\sf-backup\node_modules\request\request.js:1128:39)
    at Request.emit (events.js:388:22)
    at IncomingMessage.<anonymous> (C:\Users\w102057\Developer\sf-backup\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_STRING_TOO_LONG'
}
```

Here's the snipper of the code that I use to do this:
```
let cipher = crypto.createCipheriv('aes-256-ctr', Buffer.from(encryptionKey), iv);
let zip = zlib.createGzip();

const query = 'SELECT ' + object.fields.filter((field) => field.type != 'address').map((field) => field.name).join(', ') + ' FROM ' + object.name;


conn.bulk.query(query)
                    .on('end', () => resolve())
                    .on('error', function(err) { console.log(err); reject(err); })
                    .stream()
                    .pipe(zip)
                    .pipe(cipher)
                    .pipe(fs.createWriteStream(backupDir + '/' + object.name + '.csv.enc'));
```

**Comment by oscarnevarezleal** [comment]
Hi @[vpetrovych](https://github.com/vpetrovych)
Did you manage to solve this issue?

**Comment by cristiand391** [comment]
closing this, we recommend using the Bulk V2 API for this:
https://jsforce.github.io/document/#bulk-v2-api

if anyone finds a similar error please file a new issue. Thanks!
