### ISSUE TITLE
tunneling socket could not be established, cause=read ECONNRESET

### ISSUE THREAD

**Issue by manish-jain-1** [jsforce/jsforce#1178]
We are getting intermittent ECONNRESET errors connecting to Salesforce API. Is this a known issue?/any help the experts can provide? Any way to can trace this request? This only happens during high traffic - 

EDIT - could this be a rate limiting issue on the SF API? Are those errors exposed via jsforce?

Thanks in advance!

```
{ Internal Server Error: Could not get Cases, probably problems with Salesforce.
    at new funcObj.(anonymous function) (//code/src/base/errorHandling/custom_error.js:28:16)
    at _getCasesForUser (//code/src/base/services/case_service.js:30:25)
    at _loadCasesForAccount (/code/src/base/services/case_service.js:288:23)
    at sfConnectionService.queryFromSalesforce (/code/src/base/services/case_service.js:269:16)
    at async.whilst (//code//src/base/services/salesforce_connection_service.js:151:18)
    at //code/node_modules/async/dist/async.js:969:16
    at next (//code/node_modules/async/dist/async.js:5222:25)
    at sforce.queryMore (//code/src/base/services/salesforce_connection_service.js:140:22)
    at promiseCallback (//code//node_modules/jsforce/lib/query.js:337:15)
    at module.exports.<anonymous> (//code//node_modules/jsforce/lib/query.js:353:5)
    at Object.onceWrapper (events.js:286:20)
    at module.exports.emit (events.js:198:13)
    at //code//node_modules/jsforce/lib/query.js:383:10
    at tryCallOne (//code/node_modules/promise/lib/core.js:37:12)
    at //code//node_modules/promise/lib/core.js:123:15
    at flush (//code//node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  name: 'Internal Server Error',
  initialError:
   { Error: tunneling socket could not be established, cause=read ECONNRESET
       at ClientRequest.onError (//code//node_modules/tunnel-agent/index.js:177:17)
       at Object.onceWrapper (events.js:286:20)
       at ClientRequest.emit (events.js:198:13)
       at Socket.socketErrorListener (_http_client.js:401:9)
       at Socket.emit (events.js:198:13)
       at emitErrorNT (internal/streams/destroy.js:91:8)
       at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
       at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' },
  status: 500,
```

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
