### ISSUE TITLE
Describe unable to find the sobject but is available using Metadata API

### ISSUE THREAD

**Issue by bznteli** [jsforce/jsforce#1299]
Has anyone run into this?

NOT_FOUND: The requested resource does not exist
    at HttpApi.getError (/Users/bz/Documents/jsprojects/node-dataloader/node_modules/jsforce/lib/http-api.js:250:13)
    at /Users/bz/Documents/jsprojects/node-dataloader/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/Users/bz/Documents/jsprojects/node-dataloader/node_modules/promise/lib/core.js:37:12)
    at /Users/bz/Documents/jsprojects/node-dataloader/node_modules/promise/lib/core.js:123:15
    at flush (/Users/bz/Documents/jsprojects/node-dataloader/node_modules/asap/raw.js:50:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errorCode: 'NOT_FOUND'

I'm trying to access the CareProgram (Standard) object in Health Cloud and am unable to perform any upserts that relate to this field or have anything to do with this sobject.

Profile has full access to the object b/c I can run SOQL query on it using DevConsole.

**Comment by cristiand391** [comment]
triaging old issues...

to rule out any perm issues you can always run the soql query via jsforce using the same user.
on jsforce v3 you can enable debug output by setting the `JSFORCEL_LOG_LEVEL=DEBUG` env var to see what requests are being done.
