### ISSUE TITLE
SOQL query returns user data always

### ISSUE THREAD

**Issue by polosatyi** [jsforce/jsforce#1335]
Hey guys, maybe someone can help me. I'm trying to make SOQL queries using jsforce.

```
...
const conn =  Connection({
  instanceUrl: integration.instanceUrl,
  accessToken: integration.accessToken,
});

const soql = `SELECT Id FROM Opportunity WHERE Id = '${opportunityId}'`;
const result = await connection.query<T>(soql);
console.log(result);
...
```

No matter what SOQL I pass, I get the following result all the time:
```
{
 "id": "https://login.salesforce.com/id/***/***",
 "asserted_user": true,
 "user_id": "***",
 "organization_id": "***",
 "username": "***",
 "nick_name": "***",
 "display_name": "***",
 "email": "***",
 "email_verified": true,
 "first_name": "***",
 "last_name": "***",
 "timezone": "***",
 "photos": {
   "picture": "***",
   "thumbnail": "***"
 },
 "addr_street": null,
 "addr_city": null,
 "addr_state": null,
 "addr_country": "***",
 "addr_zip": null,
 "mobile_phone": null,
 "mobile_phone_verified": false,
 "is_lightning_login_user": false,
 "status": {
   "created_date": null,
   "body": null
 },
 "urls": {
   "enterprise": "https://***.develop.my.salesforce.com/services/Soap/c/{version}/***",
   "metadata": "https://***.develop.my.salesforce.com/services/Soap/m/{version}/***",
   "partner": "https://***.develop.my.salesforce.com/services/Soap/u/{version}/***",
   "rest": "https://***.develop.my.salesforce.com/services/data/v{version}/",
   "sobjects": "https://***.develop.my.salesforce.com/services/data/v{version}/sobjects/",
   "search": "https://***.develop.my.salesforce.com/services/data/v{version}/search/",
   "query": "https://***.develop.my.salesforce.com/services/data/v{version}/query/",
   "recent": "https://***.develop.my.salesforce.com/services/data/v{version}/recent/",
   "tooling_soap": "https://***.develop.my.salesforce.com/services/Soap/T/{version}/***",
   "tooling_rest": "https://***.develop.my.salesforce.com/services/data/v{version}/tooling/",
   "profile": "https://***.develop.my.salesforce.com/***",
   "feeds": "https://***.develop.my.salesforce.com/services/data/v{version}/chatter/feeds",
   "groups": "https://***.develop.my.salesforce.com/services/data/v{version}/chatter/groups",
   "users": "https://***.develop.my.salesforce.com/services/data/v{version}/chatter/users",
   "feed_items": "https://***.develop.my.salesforce.com/services/data/v{version}/chatter/feed-items",
   "feed_elements": "https://***.develop.my.salesforce.com/services/data/v{version}/chatter/feed-elements",
   "custom_domain": "https://***.develop.my.salesforce.com"
 },
 "active": true,
 "user_type": "STANDARD",
 "language": "en_US",
 "locale": "en_GB",
 "utcOffset": 0,
 "last_modified_date": "2022-12-07T21:56:31Z",
 "is_app_installed": true
}
```

What am I doing wrong? jsforce version is 1.11.1. Tried to set the API version (55.0, 49.0, etc).

**Comment by polosatyi** [comment]
Tried with `jsforce@2.0.0-beta.23`, got an error:
```
TypeError: Cannot read properties of undefined (reading 'length')
  at Query._execute (/srv/***/node_modules/jsforce/lib/query.js:420:205)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async /***/flowla/node_modules/jsforce/lib/query.js:346:9
```

**Comment by cristiand391** [comment]
I'm going to close this because I'm pretty sure this was related to the instance URL (can't recall which endpoint returns that response). That code should work, example:
https://jsforce.github.io/document/#query

if someone finds a similar problem please log a new issue.
