### ISSUE TITLE
 TypeError: Cannot read property 'objectMode' of undefined( node_modules/readable-stream/lib/_stream_writable.js:317:22)

### ISSUE THREAD

**Issue by manish-space** [jsforce/jsforce#1396]
I'm encountering an intermittent error while utilizing JSForce ("jsforce": "^1.11.1") for interacting with Salesforce and performing update operations on the Feed & Task object. The frequency of occurrence of this error is gradually increasing.
Any help is appreciated, Thanks !

```
updateActivity error: TypeError: Cannot read property 'objectMode' of undefined
at RecordStream.Serializable.Writable.write (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_writable.js:317:22)
at module.exports.ondata (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_readable.js:619:20)
at module.exports.emit (events.js:315:20)
at module.exports.EventEmitter.emit (domain.js:482:12)
at addChunk (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_readable.js:291:12)
at readableAddChunk (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_readable.js:278:11)
at module.exports.Readable.push (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_readable.js:245:10)
at /home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/jsforce/lib/query.js:445:12
at tryCallOne (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/promise/lib/core.js:37:12)
at /home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/promise/lib/core.js:123:15
at flush (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/asap/raw.js:50:29)
at processTicksAndRejections (internal/process/task_queues.js:79:11)
Error: TypeError: Cannot read property 'objectMode' of undefined
at RecordStream.Serializable.Writable.write (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_writable.js:317:22)
at module.exports.ondata (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_readable.js:619:20)
at module.exports.emit (events.js:315:20)
at module.exports.EventEmitter.emit (domain.js:482:12)
at addChunk (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_readable.js:291:12)
at readableAddChunk (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_readable.js:278:11)
at module.exports.Readable.push (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/readable-stream/lib/_stream_readable.js:245:10)
at /home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/jsforce/lib/query.js:445:12
at tryCallOne (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/promise/lib/core.js:37:12)
at /home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/promise/lib/core.js:123:15
at flush (/home/samespace-serverless-1964/functions/65adf6d19d623b0218240c23/node_modules/asap/raw.js:50:29)
at processTicksAndRejections (internal/process/task_queues.js:79:11)
offline: (λ: integ) RequestId: cls8m7nhv00i4jvvm2onc1egm Duration: 14346.08 ms Billed Duration: 14347 ms

```

**Comment by cristiand391** [comment]
Hi, a few questions:

1) node version used? 
2) from logs this seem to run on a serverless env, are you sure it's run using node and not other runtimes like deno and bun?

**Comment by cristiand391** [comment]
I'm not sure exactly what could cause this (you mention it's intermittent), jsforce v1 uses `readable-stream` v1:
https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/package.json#L70

jsforce v2 and v3 used `readable-stream` v2 (via `stream-browserify`), I would wait until the v3 GA to see if it's replicable.

**Comment by manish-space** [comment]
Yes, it's intermittent but the frequency of occurrence of this error is gradually increasing.
Thanks!
