### ISSUE TITLE
Issue 979 still exists ( cannot find user home directory to store configuration files )

### ISSUE THREAD

**Issue by shubsaini09** [jsforce/jsforce#1409]
Hello, I see that [979](https://github.com/jsforce/jsforce/issues/979) was fixed by [1336](https://github.com/jsforce/jsforce/pull/1336) but I am still facing the same issue in the jsforce version `3.1.0`

I can resolve it by applying this [answer](https://github.com/jsforce/jsforce/issues/979#issuecomment-571627907) but do I still need to do this after the actual fix?

Did you face any issues after your fix? @dylandechant 

```
Error: cannot find user home directory to store configuration files
    at getDefaultConfigFilePath (/opt/nodejs/node_modules/jsforce/lib/registry/file.js:16:15)
    at new FileRegistry (/opt/nodejs/node_modules/jsforce/lib/registry/file.js:27:50)
    at Object.<anonymous> (/opt/nodejs/node_modules/jsforce/lib/registry/index.js:15:15)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/nodejs/node_modules/jsforce/lib/jsforce.js:35:36)
```

**Comment by cristiand391** [comment]
closing as dup of #979
