### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END in Bulk2 Query for CampaignMember

### ISSUE THREAD

**Issue by brantian** [jsforce/jsforce#1546]
I'm trying to migrate from using Bulk API v1 to v2, but I'm experiencing some issues specifcally when trying to fetch `CampaignMembers`

I'm using @jsforce/jsforce-node 3.3.1.

If I use Bulk API v1 to run a CampaignMember query, "Stream ended" is shown in console as expected:

```JS
    const stream = await connection.bulk.query("SELECT Id FROM CampaignMember WHERE SystemModstamp >= 2024-07-01T00:00:00.000Z")

    stream.on('record', () => {})
    .on('end', () => console.log('Stream ended'))
    .on('error', (error) => {
        console.log('Stream error:', error)
    })
    
   // "Stream ended" shown in console
```

However, If I try the same query, but using Bulk API v2 I get an error:

```JS
    const stream = await connection.bulk2.query("SELECT Id FROM CampaignMember WHERE SystemModstamp >= 2024-07-01T00:00:00.000Z")

    stream.on('record', () => {})
    .on('end', () => console.log('Stream ended'))
    .on('error', (error) => {
        console.log('Stream error:', error)
    })
```

This throws:

node:events:497
      throw er; // Unhandled 'error' event
      ^

```
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end   
    at _write (node:internal/streams/writable:481:11) 
    at Writable.write (node:internal/streams/writable:502:10)
    at DuplexifiedStream.ondata (node:internal/streams/readable:1007:22)
    at DuplexifiedStream.emit (node:events:519:28)    
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at DuplexifiedStream._readStream (D:\Repositories\demandlab\insentric-sfdc\node_modules\@jsforce\jsforce-node\lib\util\stream.js:81:18)
    at PassThrough.<anonymous> (D:\Repositories\demandlab\insentric-sfdc\node_modules\@jsforce\jsforce-node\lib\util\stream.js:64:18)
    at PassThrough.emit (node:events:519:28)
Emitted 'error' event on PassThrough instance at:     
    at PassThrough.onerror (node:internal/streams/readable:1026:14)
    at PassThrough.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

Note that the error is not emitted by the stream.

It seems that this only happens for querying `CampaignMember` using Bulk API v2. If I use v2 to bulk query other objects it works as expected. This shows "Stream ended" in console as expected

```JS
    const stream = await connection.bulk2.query("SELECT Id FROM Account WHERE SystemModstamp >= 2024-07-01T00:00:00.000Z")

    stream.on('record', () => {})
    .on('end', () => console.log('Stream ended'))
    .on('error', (error) => {
        console.log('Stream error:', error)
    })
```

**Comment by cristiand391** [comment]
hey, sorry for the late reply.

How many `CampaignMember` records do you have? I'm not able to repro but just have a few thousands

**Comment by brantian** [comment]
In total, I have ~ 1.6 million `CampaignMember`

However, I'm filtering by `SystemModstamp`, and even if I get `CampaignMember` from a single day (less than a thousand records), I still get the same error.

But now, while re-testing with `@jsforce/jsforce-node 3.4.1` I noticed that if I **don't** add the `SystemModstamp` filter the query works, I can see the records being processed by using `stream.on('record', console.log)` but then the stream ends silently when I reach 999.999 records (probably related to #697)

If I add `SystemModstamp` filter to the query, I get the `[ERR_STREAM_WRITE_AFTER_END]: write after end` without seeing any records being processed.
