### ISSUE TITLE
Issue connecting to salesforce for version 3

### ISSUE THREAD

**Issue by chidibede** [jsforce/jsforce#1561]
I have issues connecting to salesforce after upgrading to version 3.4.1, if I downgrade back to version 1, it connects successfully.

This is the code
```
export const getSalesforceConnection = async () => {
             const SALESFORCE_FULL_TOKEN = SALESFORCE_PASSWORD + SALESFORCE_TOKEN;
             const conn = new Connection({
                                        loginUrl: SALESFORCE_LOGIN_URL,
                                    });
             await conn.login(SALESFORCE_USERNAME, SALESFORCE_FULL_TOKEN)
             return conn
 }
```

Running it in a lambda node Runtime: nodejs18.x and lambda Architectures: - x86_64

The error thrown is
```{
            "errorType": "TypeError",
            "errorMessage": "Expected signal to be an instanceof AbortSignal",
            "stackTrace": [
                "TypeError: Expected signal to be an instanceof AbortSignal",
                "    at jt (/tmp/tmp6290jf_1/node_modules/node-fetch/lib/index.js:1244:10)",
                "    at <anonymous> (/tmp/tmp6290jf_1/node_modules/node-fetch/lib/index.js:1449:19)",
                "    at new Promise (<anonymous>)",
                "    at pi (/tmp/tmp6290jf_1/node_modules/node-fetch/lib/index.js:1447:9)",
                "    at execFn (/tmp/tmp6290jf_1/node_modules/jsforce/lib/request.js:128:48)",
                "    at s5 (/tmp/tmp6290jf_1/node_modules/jsforce/lib/request-helper.js:90:21)",
                "    at startFetchRequest (/tmp/tmp6290jf_1/node_modules/jsforce/lib/request.js:176:42)",
                "    at D5 (/tmp/tmp6290jf_1/node_modules/jsforce/lib/request.js:208:5)",
                "    at builder (/tmp/tmp6290jf_1/node_modules/jsforce/lib/transport.js:66:63)",
                "    at Function.create (/tmp/tmp6290jf_1/node_modules/jsforce/lib/util/promise.js:17:37)"
            ]
        }```

**Comment by cristiand391** [comment]
that error comes from node-fetch:
https://github.com/node-fetch/node-fetch/blob/9b9d45881e5ca68757077726b3c0ecf8fdca1f29/src/request.js#L129

we use `abort-controller` here:
https://github.com/jsforce/jsforce/blob/506754881681be31daa891d09e8daaa741ceec59/src/request.ts#L4C30-L4C46

questions:
1. can you share the specific node version and platform where it's failing?
2. can you repro it locally on using the same node version?

**Comment by olliebatch** [comment]
Hey i've just run into the exact same thing, 

But i fixed it by adding [keep names](https://esbuild.github.io/api/#keep-names) to the build step.
as per https://github.com/jsforce/jsforce/issues/1399
