### ISSUE TITLE
Invalid URI "/services/data/v32.0/sobjects/Contact/describe"

### ISSUE THREAD

**Issue by thehydroimpulse** [jsforce/jsforce#188]
jsforce has mostly been working correctly. However, I've been hitting this error lately and I'm not sure what's going on.

Here's my connection setup:

```js
self.conn = new jsforce.Connection({
  instanceUrl: card.get('instanceUrl'),
  accessToken: card.get('accessKey'),
  refreshToken: card.get('refreshToken'),
  oauth2: {
    clientId: config.consumerKey,
    clientSecret: config.consumerSecret,
    redirectUri: config.redirectUrl
  }
});
```

And my query that errors out:

```js
self.conn.sobject('Contact')
  .find({ OwnerId: self._sid })
```

Stack trace:

```
Unhandled rejection Error: Invalid URI "/services/data/v33.0/sobjects/Contact/describe"
  │   at Request.init (/Users/daniel/Projects/stacks/node_modules/request/request.js:413:31)
 |│   at new Request (/Users/daniel/Projects/stacks/node_modules/request/request.js:264:8)
 9│   at request (/Users/daniel/Projects/stacks/node_modules/request/index.js:50:10)
5m│   at /Users/daniel/Projects/stacks/node_modules/request/index.js:141:14
s │   at createRequest (/Users/daniel/Projects/stacks/node_modules/jsforce/lib/transport.js:88:13)
  │   at [object Object].promise.then (/Users/daniel/Projects/stacks/node_modules/jsforce/lib/transport.js:41:5)
  │   at [object Object].HttpApi.request (/Users/daniel/Projects/stacks/node_modules/jsforce/lib/http-api.js:70:47)
  │   at [object Object].Connection.request (/Users/daniel/Projects/stacks/node_modules/jsforce/lib/connection.js:320:18)
  │   at [object Object].Connection.describe.Connection.describeSObject (/Users/daniel/Projects/stacks/node_modules/jsforce/lib/c
  │nnection.js:845:15)
  │   at [object Object].$fn (/Users/daniel/Projects/stacks/node_modules/jsforce/lib/cache.js:199:10)
  │   at describeCache (/Users/daniel/Projects/stacks/node_modules/jsforce/lib/query.js:535:10)
──┤ at expandAsteriskField (/Users/daniel/Projects/stacks/node_modules/jsforce/lib/query.js:547:7)
- │   at /Users/daniel/Projects/stacks/node_modules/jsforce/lib/query.js:507:50
[n│   at Function._.map._.collect (/Users/daniel/Projects/stacks/node_modules/underscore/underscore.js:164:24)
```

Thoughts?

**Comment by stomita** [comment]
The error message seems the connection cannot build URL for API request. Confirm that `card.get('instanceUrl')` surely has the instance URL (e.g. https://na1.salesforce.com).

**Comment by thehydroimpulse** [comment]
@stomita ahh, that was it. Thanks!
