### ISSUE TITLE
Using proxyUrl in Connection is not allowed

### ISSUE THREAD

**Issue by changusmc** [jsforce/jsforce#209]
Hello,

I'm trying to use jsforce to connect to my Production Salesforce instance and I'm running into CORS issues. I tried to use proxyUrl, but in my Chrome Dev Console, I'm seeing a ton of these errors when my code is making SOAP API calls.

```
Error: Proxying endpoint is not allowed.
    at 17.k.getError (http://cdnjs.cloudflare.com/ajax/libs/jsforce/1.4.1/jsforce.min.js:3:23763)
    at http://cdnjs.cloudflare.com/ajax/libs/jsforce/1.4.1/jsforce.min.js:3:22114
    at d (http://cdnjs.cloudflare.com/ajax/libs/jsforce/1.4.1/jsforce.min.js:7:28673)
    at 60.p.then.l.nextTick.h.promiseDispatch.j (http://cdnjs.cloudflare.com/ajax/libs/jsforce/1.4.1/jsforce.min.js:7:28946)
    at p.60.d.promiseDispatch (http://cdnjs.cloudflare.com/ajax/libs/jsforce/1.4.1/jsforce.min.js:7:23206)
    at http://cdnjs.cloudflare.com/ajax/libs/jsforce/1.4.1/jsforce.min.js:7:21978
    at Array.b (http://cdnjs.cloudflare.com/ajax/libs/jsforce/1.4.1/jsforce.min.js:7:26369)
    at c (http://cdnjs.cloudflare.com/ajax/libs/jsforce/1.4.1/jsforce.min.js:6:21476)
```

Here's my JS code to connect, I'm using jsforce-ajax-proxy locally.

```javascript
        var CONN = new jsforce.Connection({
          // you can change loginUrl to connect to sandbox or prerelease env.
          // loginUrl : 'https://test.salesforce.com'
          proxyUrl: 'http://localhost:3123/proxy',
          logLevel: 'DEBUG'
        });
        CONN.login(USER, PASSWORD, function(err, userInfo) {
          if (err) { return console.error(err); }
          // Now you can get the access token and instance URL information.
          // Save them to establish connection next time.
          console.log(CONN.accessToken);
          console.log(CONN.instanceUrl);
          // logged in user property
          console.log("User ID: " + userInfo.id);
          console.log("Org ID: " + userInfo.organizationId);
          // ...
        });
```

**Comment by stomita** [comment]
If you do login using username/password in your web JavaScript code, you should set `loginUrl` in your connection constructor. Apparently OAuth is much preferable to establish the connection in web apps, though.
