### ISSUE TITLE
metadata retrieve, combine stream() + complete() 

### ISSUE THREAD

**Issue by GeneGenie** [jsforce/jsforce#252]
Hi guys, probably i have a silly question. BUT 
you have a doc section wich describes meta retrieving as simple as it is 
conn.metadata.retrieve(options)
             .stream().pipe(fs.createWriteStream("./path/to/MyPackage.zip"))
OK. But if current user doesn't have a permission for Metadata section, it just throws unhandled exception. It can be something like this 
`{"error":{},"trace":"Error: INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission\n    at /usr/skyfence/management/entitlements/node_modules/jsforce/lib/soap.js:57:15\n    at _fulfilled (/usr/skyfence/management/entitlements/node_modules/jsforce/node_modules/q/q.js:798:54)\n    at self.promiseDispatch.done (/usr/skyfence/management/entitlements/node_modules/jsforce/node_modules/q/q.js:827:30)\n    at Promise.promise.promiseDispatch (/usr/skyfence/management/entitlements/node_modules/jsforce/node_modules/q/q.js:760:13)\n    at /usr/skyfence/management/entitlements/node_modules/jsforce/node_modules/q/q.js:574:44\n    at flush (/usr/skyfence/management/entitlements/node_modules/jsforce/node_modules/q/q.js:108:17)\n    at process._tickCallback (node.js:419:13)"}`

You also hame a complete() cb   which has error handling, BUT how can i get readable stream after this? 

     .complete(function(err,res){         
                var s = new stream.Readable();            
                s.push(res.zipFile);
                s.push(null);
                s.pipe(unzip.Parse()).on('entry', function (entry) {  .... }  //error here
     }

in this case i have 
'Error: invalid signature: 0x44734555\n    at e:\\SkyfenceParsers\\node_modules\\unzip\\lib\\parse.js:59:13\n    at processImmediate [as _immediateCallback] (timers.js:345:15)'

probably i'm doing something wrong

**Comment by GeneGenie** [comment]
Nevermind. Solved this by base64 decoding zipFile 
so   zipFile -> base64 decode -> Buffer -> readable stream -> pipe -> unzip
