### ISSUE TITLE
http_proxy/https_proxy not working with streaming api (server-side)

### ISSUE THREAD

**Issue by joeferraro** [jsforce/jsforce#279]
jsforce 1.5.0
osx 10.10

When http_proxy/https_proxy are configured, I'm unable to subscribe to streaming channels. I found that somehow `tunnel-agent`'s addRequest function is receiving improper host/port arguments (if I hardcode host and port to my proxy values, it works). I'm not sure whether this may be something in the way proxy settings are passed to Faye/request in jsforce-api-streaming.

```
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:51:11)
    at TunnelingAgent.exports.request (http.js:30:10)
    at TunnelingAgent.createSocket (my-app/node_modules/tunnel-agent/index.js:127:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (my-app/node_modules/tunnel-agent/index.js:194:41)
    at TunnelingAgent.addRequest (my-app/node_modules/tunnel-agent/index.js:90:8)
    at new ClientRequest (_http_client.js:133:16)
    at Object.exports.request (http.js:30:10)
    at Object.exports.request (https.js:115:15)
    at Object.Faye.Transport.NodeHttp.Faye.extend.Faye.Class.request (my-app/node_modules/faye/node/faye-node.js:2650:36)
    at Object.Faye.Transport.Faye.extend.Faye.Class.sendMessage (my-app/node_modules/faye/node/faye-node.js:1693:60)
    at Object.Faye.Dispatcher.Faye.Class._sendEnvelope (my-app/node_modules/faye/node/faye-node.js:1568:40)
    at Object.Faye.Dispatcher.Faye.Class.sendMessage (my-app/node_modules/faye/node/faye-node.js:1546:10)
    at Object.<anonymous> (my-app/node_modules/faye/node/faye-node.js:1395:24)
    at Object.Faye.Extensible.pipeThroughExtensions (my-app/node_modules/faye/node/faye-node.js:919:44)
    at Object.Faye.Client.Faye.Class._sendMessage (my-app/node_modules/faye/node/faye-node.js:1392:10)
    at Object.Faye.Client.Faye.Class.handshake (my-app/node_modules/faye/node/faye-node.js:1175:10)
```

**Comment by joeferraro** [comment]
this issue seems to be inconsistent. closing until i can provide more info.

**Comment by cwarden** [comment]
@joeferraro, did you ever dig into this further?  Is this a faye issue?

sfdx seems to be affected by this as well.  The subscription to `/event/OrgLifecycleNotification` created when `sfdx force:org:create` is run ignores the `http_proxy` environment variable.

**Comment by cwarden** [comment]
Looks like a different issue.  My problem was that faye requires `https_proxy` to be set in order to proxy https connections, rather than just `http_proxy`.
