### ISSUE TITLE
Metadata API errors not sent to callback

### ISSUE THREAD

**Issue by jdcrensh** [jsforce/jsforce#289]
The _invoke method in metadata.js is not sending any API errors to the callback function.

**Comment by marcmarcet** [comment]
I'm experiencing the same issue. Will try to find the issue sometime this week.

**Comment by ra-ryan** [comment]
Any updates on this issue? I'm having the same problem when polling times out on a long metadata request. When this happens, the completely app crashes and outputs the error below. I increased the polling timeout length for the time being but would rather find a fix so that the error can be caught without the app crashing.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Polling time out. Process Id = 09Sj0000002qaiCEAQ
    at poll [as _onTimeout] (/.../node_modules/jsforce/lib/api/metadata.js:660:26)
    at Timer.listOnTimeout (timers.js:92:15)
```
