### ISSUE TITLE
Tooling#completions() fails

### ISSUE THREAD

**Issue by stomita** [jsforce/jsforce#33]
Raises following error:

```
UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 179754945-35410 (-1975115202)
      at onResponse (/Users/stomita/Work/Salesforce/jsforce/lib/connection.js:330:13)
      at _fulfilled (/Users/stomita/Work/Salesforce/jsforce/node_modules/q/q.js:798:54)
      at self.promiseDispatch.done (/Users/stomita/Work/Salesforce/jsforce/node_modules/q/q.js:827:30)
      at Promise.promise.promiseDispatch (/Users/stomita/Work/Salesforce/jsforce/node_modules/q/q.js:760:13)
      at /Users/stomita/Work/Salesforce/jsforce/node_modules/q/q.js:574:44
      at flush (/Users/stomita/Work/Salesforce/jsforce/node_modules/q/q.js:108:17)
      at process._tickCallback (node.js:415:13)
```

**Comment by cristiand391** [comment]
Seems this was fixed in the last ~10 years 😄 

hit the tooling/completions endpoint with curl and empty Accept/content-type headers (you have to set them to empty or it will set curl's defaults).

![Screenshot 2024-05-20 at 6 54 36 PM](https://github.com/jsforce/jsforce/assets/6853656/edd8aef7-2963-408a-9916-c2ce633b2e3b)
