### ISSUE TITLE
OAuth2 Flow In GovCloud instances - Get Invalid Sessio Id

### ISSUE THREAD

**Issue by Vishalashah** [jsforce/jsforce#386]
On the https://jsforce.github.io/document/ page after logging in to a GovCloud instance, we receive the below error:
`INVALID_SESSION_ID: Session expired or invalid
    at h.getError (https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.6.0/jsforce.min.js:2:29665)
    at https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.6.0/jsforce.min.js:2:28015
    at o (https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.6.0/jsforce.min.js:7:15718)
    at https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.6.0/jsforce.min.js:7:16461
    at MutationObserver.r (https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.6.0/jsforce.min.js:7:18852)`

**Comment by Vishalashah** [comment]
The issue was that the Org's Session Settings were enabled. Disabling it, solved our problem.

> Lock sessions to the IP address from which they originated
