### ISSUE TITLE
Query and Search functions cause socket hang up

### ISSUE THREAD

**Issue by cinnamonKale** [jsforce/jsforce#610]
When making a Salesforce database request using either SOQL or SOSL, my production server keeps timing out. Code:

```
// ====================
// Salesforce OAuth2
// ====================

const oauth2 = new jsforce.OAuth2({
  loginUrl: 'https://login.salesforce.com',
  clientId: config[env]['salesforce']['clientId'],
  clientSecret: config[env]['salesforce']['clientSecret'],
  redirectUri: config[env]['salesforce']['redirectUri']
})

// Get authorization URL and redirect to it.
app.get('/oauth2/auth', function (req, res) {
  res.redirect(oauth2.getAuthorizationUrl())
})

// Pass received authorization code and get access token
app.get('/oauth2/callback', function (req, res) {
  var conn = new jsforce.Connection({ oauth2: oauth2 })
  const code = req.param('code')

  conn.authorize(code).then(function (userInfo) {
    // Now you can get the access token, refresh token, and instance URL information.
    // Save them to establish connection next time.
    console.log(`Access: ${conn.accessToken}`)
    console.log(`Refresh: ${conn.refreshToken}`)
    console.log(`Instance: ${conn.instanceUrl}`)
    console.log(`User ID: ${userInfo.id}`)
    console.log(`Org ID: ${userInfo.organizationId}`)

    req.session.accessToken = conn.accessToken
    req.session.instanceUrl = conn.instanceUrl
    req.session.userId = userInfo.id

    res.cookie('sf_access', conn.accessToken, {
      secure: true
    })

    res.redirect('/dashboard')
  }).catch(function (err) {
    console.error(err)
    res.redirect('/')
  })
})

// SF callback redirects to /dashboard
app.get('/dashboard', function (req, res, next) {
  // If auth has not been set, redirect to index
  if (!req.session.accessToken || !req.session.instanceUrl || !req.session.userId) {
    res.redirect('/')
  }

  // Open connection with client's stored OAuth details
  const conn = new jsforce.Connection({
    accessToken: req.session.accessToken,
    instanceUrl: req.session.instanceUrl,
    logLevel: 'DEBUG'
  })

  // Test queries
  // Use SOSL for faster searching
  const searchOpps = 'FIND {"Edge} RETURNING Opportunity(Name)'
  // Uses SOQL
  const queryUser = `SELECT Name FROM User WHERE Id = '${req.session.userId}'`

  // Make the query call
  conn.query(queryUser).then(function (result) {
    // Add the result to a bigger results array
    var resultsAll = [{ 'Name': result.records[0]['Name'] }]

    // Make the search call, then send results to the page
    // Add within the first promise so we can access its data
    conn.search(searchOpps).then(function (result) {
      // Add new results to the bigger array
      resultsAll.push({ 'Opportunities': result })

      // Send all the results
      res.send(resultsAll)
    }).catch(function (err) {
      console.error(err)
      res.redirect('/')
    })
  }).catch(function (err) {
    console.error(err)
    res.redirect('/')
  })
})
```

Error log from server:

```
>>> Query start >>>
SOQL = SELECT Name FROM User WHERE Id = 'XXXXXXXXXXXX'
<request> method=GET, url=https://na40.salesforce.com/services/data/v37.0/query?q=SELECT%20Name%20FROM%20User%20WHERE%20Id%20%3D%20'XXXXXXXXXXXX'
elappsed time : 120021msec
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1117:19)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
--- Query error ---
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1117:19)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

And error from CLI:

```
// Already ran .register and .authenticate using creds
> query('SELECT Name FROM User LIMIT 10')
{ Error: connect ETIMEDOUT 136.147.109.40:443
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '136.147.109.40',
  port: 443 }
Error: connect ETIMEDOUT 136.147.109.40:443
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

FWIW, I can successfully authenticate using both my Node app and the jsforce CLI. I can also make the same database calls locally and on a test server, but I've confirmed there's nothing on the production server to block traffic between the server and external sources.

Any help is appreciated, I'm out of my depth right now trying to debug server errors.

Node: 7.5.0
npm: 4.1.2
jsforce: ^1.7.1

**Comment by thanneeruvenu** [comment]
come across same issue, solved the issue with adding try catch block.
hope it will helpful. :)

**Comment by jtushman** [comment]
@thanneeruvenu can you show me your psydocode.  what did you wrap with try/catch and how did you handle retry?

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
