### ISSUE TITLE
Error: Invalid URI "/services/data/v39.0/query?q=SELECT...."

### ISSUE THREAD

**Issue by neeraj87** [jsforce/jsforce#645]
When I call jsforce the first time (after the user is logged in) and then run the query it works fine. Then second time it throws me this error:

`Error: Invalid URI "/services/data/v39.0/query?q=SELECT...."`

Here is my query code

```
var conn = new jsforce.Connection({
		instanceUrl: req.session.instanceUrl,
		accessToken: req.session.accessToken
    });

conn.query(proposalQueryString, function(err, result) {
		if (err) {
			return console.error(err);
		}
		for(var i = 0; i < result.records.length; i++) {
			//get records in list
		}

	});
```
Here is the error log from Heroku

```
Error: Invalid URI "/services/data/v39.0/query?q=SELECT%20Id%2C%20Name%2C%20Status__c%2C%20Client__c%2C%20CreatedDate%2C%20Broker_Proposed_Price__c%2C%20Date_of_First_Appointment__c%2C%20Date_Proposal_Requested__c%20FROM%20Proposal__c%20limit%204"
2017-05-23T15:51:30.968358+00:00 app[web.1]:     at Request.init (/app/node_modules/request/request.js:276:31)
2017-05-23T15:51:30.968359+00:00 app[web.1]:     at new Request (/app/node_modules/request/request.js:130:8)
2017-05-23T15:51:30.968360+00:00 app[web.1]:     at request (/app/node_modules/request/index.js:54:10)
2017-05-23T15:51:30.968360+00:00 app[web.1]:     at /app/node_modules/request/index.js:101:12
2017-05-23T15:51:30.968361+00:00 app[web.1]:     at createRequest (/app/node_modules/jsforce/lib/transport.js:84:13)
2017-05-23T15:51:30.968362+00:00 app[web.1]:     at Promise.promise.then (/app/node_modules/jsforce/lib/transport.js:43:5)
2017-05-23T15:51:30.968362+00:00 app[web.1]:     at HttpApi.request (/app/node_modules/jsforce/lib/http-api.js:82:47)
2017-05-23T15:51:30.968363+00:00 app[web.1]:     at Connection.request (/app/node_modules/jsforce/lib/connection.js:325:18)
2017-05-23T15:51:30.968367+00:00 app[web.1]:     at /app/node_modules/jsforce/lib/query.js:407:23
2017-05-23T15:51:30.968368+00:00 app[web.1]:     at tryCallOne (/app/node_modules/promise/lib/core.js:37:12)
```

Why does it say invalid URI? There is no issue with user login as both accessToken and instanceUrl are generated.

Any idea?

**Comment by SonamTcheu** [comment]
Hi neeraj87,

I have same error. Do you find where the errors comes from ?

Thanks,

**Comment by neeraj87** [comment]
@SonamTcheu it turns out that on my router the req.session.accessToken was coming as null. In short the accessToken was not being set. It was my own fault. I would suggest printing req.session.accessToken and req.session.instanceUrl on each route.
